### ISSUE TITLE
Issue with registering custom post types

### ISSUE THREAD

**Issue by aleksioconnor** [digitoimistodude/air-light#98] opened 2021-05-05 19:06 UTC
Hi!

I'm developing with air-light using Local by Flywheel. I'm also using devpackages. No problems so far. However:

**Issue**

I've followed the instructions [for registering custom post types](https://github.com/digitoimistodude/air-light#custom-post-types). I added your-post-type.php under inc/post-types. I uncommented the code in functions.php:

`'post_types' => [
  'your-post-type' => 'Your_Post_Type',
  ],`

Wordpress crashes and I am greeted with the error:

`Fatal error: Class 'Air_Light\Post_Type' not found in /app/public/wp-content/themes/mycustomtheme/inc/post-types/your-post-type.php on line 16`

Is this error caused by my development environment, or is there a step that I am missing? I have been trying to troubleshoot this problem without success.

Thank you for the great theme, any help at all is greatly appreciated!

**Comment by timiwahalahti** [comment] 2021-05-05 20:25
Hi @aleksioconnor, nice that you use our theme!

Just to double-check, are you using the same syntax in your file that we have in the [example](https://github.com/digitoimistodude/air-light/blob/master/inc/post-types/your-post-type.php)?

Could you share the custom post type file you're using, to help debug the issue - thanks :) To our knowledge, the theme should work just fine with Local by Flywheel.

**Comment by Niq1982** [comment] 2021-05-06 03:55
Have you installed the theme from WordPress theme directory? Because in that case the post type registering is disabled due to WordPress theme guidelines not allowing CPT registering in themes. 

Clone the theme from github or just copy the files from inc/post-types and inc/taxonomies and include them in  includes.php

**Comment by ronilaukkarinen** [comment] 2021-05-06 05:19
Please note: If you use the dev version of the theme you will have Air-light related dotfiles, gulpfiles etc. that may interfere with the settings and linters you have in the project level. I have clarified this section in the documentation.

The CPT documentation can be found [here](https://github.com/digitoimistodude/air-light/wiki/Using-with-Local-by-Flywheel-or-other-3rd-party-development-environment#development-steps-and-custom-post-types-cpts) (it has been always there but I have made it more clear with examples and sub titles).

I'm going to close this issue but please let us know @aleksioconnor if you got it solved or if the problem is in our end!

**Closed by ronilaukkarinen** 2021-05-06 05:19 UTC

**Comment by aleksioconnor** [comment] 2021-05-06 08:00
Hi,

Thanks for all the replies. I installed the theme from the WordPress theme directory. I was missing the includes/post-types file from the installation. Now everything is working, thanks again!
