### ISSUE TITLE
Latest update - CSS not applied

### ISSUE THREAD

**Issue by ayoubkhan558** [digitoimistodude/air-light#114] opened 2021-05-28 12:47 UTC
Latest update failed

![image](https://user-images.githubusercontent.com/20210961/119985971-2d2f7e00-bf78-11eb-8c7b-9aa1e4e80572.png)

**Comment by ronilaukkarinen** [comment] 2021-05-28 13:07
Can you please provide a little bit more information? As you can see the latest version 7.5.9 is up and running [on the demo site](https://airwptheme.com/demo/).

* What version you are using?
* What does the gulp output say?
* What does devtools console output?
* What are you trying to do?
* In what way did you apply "updates"? Air-light is not meant to be "updated" as it's a starter theme. As stated in [Please note before using](https://github.com/digitoimistodude/air-light#please-note-before-using): "Air is a development theme, so it has updates very often. By using this starter theme, you agree that the anything can change to a different direction without a warning when you look at this dev-git the next time. Please note this theme has no updates inside WordPress by design. Use this theme to hack it to pieces and create your new awesome theme based on Air!"

**Comment by ronilaukkarinen** [comment] 2021-06-07 10:15
No sufficient information provided so I'm closing this.

**Closed by ronilaukkarinen** 2021-06-07 10:15 UTC
