### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class 'Dotenv\Dotenv' not found

### ISSUE THREAD

**Issue by HannaAugust** [digitoimistodude/air-light#171] opened 2023-02-22 19:12 UTC
We are trying to set up air-light theme using dudestack with following directions: https://github.com/digitoimistodude/air-light#air-development. One step 12, while trying to activate the theme, we are running into the issue with Dotenv and so far could not find the solution for this problem:

```
PHP Fatal error:  Uncaught Error: Class 'Dotenv\Dotenv' not found in /private/var/www/airdev/config/application.php:31
Stack trace:
#0 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1296) : eval()'d code(7): require_once()
#1 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1296): eval()
#2 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php(1254): WP_CLI\Runner->load_wordpress()
#3 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php(28): WP_CLI\Runner->start()
#4 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php(78): WP_CLI\Bootstrap\LaunchRunner->process(Object(WP_CLI\Bootstrap\BootstrapState))
#5 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php(32): WP_CLI\bootstrap()
#6 phar:///usr/local/bin/wp/php/boot-phar.php(11): include('phar:///usr/loc...')
#7 /usr/local/bin/wp(4): include('phar:///usr/loc...')
#8 {main}
  thrown in /private/var/www/airdev/config/application.php on line 31
```
This issue seems to be related to dudestack and not the air-light theme itself. Is there any suggestions on what can be causing this or how to fix it?

Thank you.

**Comment by ronilaukkarinen** [comment] 2023-02-22 19:21
Sounds like you forgot to run `composer update` for your project. This issue is indeed more for dudestack, those issues belong [here](https://github.com/digitoimistodude/dudestack/issues?q=is%3Aopen+is%3Aissue) so I'm just going to close this one.

Air-light can be used with any development setup, although dudestack and macos-lemp-setup are the preferred ones for us.

What do you mean by setting up Air-light? I'm asking because that tutorial you are referring to is for improving Air-light itself. Do you want to set it up to contribute and send improvements to Air-light? Or do you want to create your own theme based on Air-light? If the case is latter, please refer to [Wiki](https://github.com/digitoimistodude/air-light/wiki).

We do not have a definitive support or instructions for our starter theme because there are endless ways to fork it. Air-light is not ready or complete by design, it's a starting point for new projects.

**Closed by ronilaukkarinen** 2023-02-22 19:21 UTC
